### ISSUE TITLE
Panic Occurs When libvirt-provider is Initialized with a Store Containing an Unreconciled Machine

### ISSUE THREAD

**Issue by so-sahu** [ironcore-dev/libvirt-provider#383]
**Describe the bug**
A panic is encountered when the `libvirt-provider` is initialized with a store that already contains a machine. This issue occurs specifically when the machine in the store has not been successfully reconciled. The panic is not observed if the machine in the store has been successfully reconciled before re-initializing the provider.

After deleting the machine from the store and re-initializing the provider, the issue is resolved, and initialization completes successfully.

**To Reproduce**
1. Ensure there is a machine in the store that has not been successfully reconciled.
2. Re-initialize the `libvirt-provider` with the same store.
3. Observe the panic error.

**Expected behavior**
The `libvirt-provider` should handle unreconciled machines in the store during initialization without causing a panic.

**Screenshots**
```
goroutine 98 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0003eec40?})
    /home/sosahu/go/pkg/mod/k8s.io/apimachinery@v0.30.3/pkg/util/runtime/runtime.go:56 +0xcd
panic({0x19c54c0?, 0x2d022d0?})
    /home/sosahu/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.6.linux-amd64/src/runtime/panic.go:770 +0x132
github.com/ironcore-dev/libvirt-provider/internal/controllers.(*MachineReconciler).startCheckAndEnqueueVolumeResize.func1({0x1f33da8, 0xc0001bab90})
    /home/sosahu/my-workspace/libvirt-provider/internal/controllers/machine_controller.go:254 +0xa22
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
    /home/sosahu/go/pkg/mod/k8s.io/apimachinery@v0.30.3/pkg/util/wait/backoff.go:259 +0x1f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
    /home/sosahu/go/pkg/mod/k8s.io/apimachinery@v0.30.3/pkg/util/wait/backoff.go:226 +0x33
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0005f5eb8, {0x1f16bc0, 0xc00058df20}, 0x1, 0xc000450000)
    /home/sosahu/go/pkg/mod/k8s.io/apimachinery@v0.30.3/pkg/util/wait/backoff.go:227 +0xaf
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000585eb8, 0xdf8475800, 0x0, 0x1, 0xc000450000)
    /home/sosahu/go/pkg/mod/k8s.io/apimachinery@v0.30.3/pkg/util/wait/backoff.go:204 +0x7f
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext({0x1f33da8, 0xc0001bab90}, 0xc000585f18, 0xdf8475800, 0x0, 0x1)
    /home/sosahu/go/pkg/mod/k8s.io/apimachinery@v0.30.3/pkg/util/wait/backoff.go:259 +0x93
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(...)
    /home/sosahu/go/pkg/mod/k8s.io/apimachinery@v0.30.3/pkg/util/wait/backoff.go:170
github.com/ironcore-dev/libvirt-provider/internal/controllers.(*MachineReconciler).startCheckAndEnqueueVolumeResize(0xc00074b9e0?, {0x1f33da8?, 0xc0001bab90?}, {{0x1f38e18?, 0xc00058def0?}, 0x0?})
    /home/sosahu/my-workspace/libvirt-provider/internal/controllers/machine_controller.go:221 +0x79
github.com/ironcore-dev/libvirt-provider/internal/controllers.(*MachineReconciler).Start.func4()
    /home/sosahu/my-workspace/libvirt-provider/internal/controllers/machine_controller.go:187 +0xce
created by github.com/ironcore-dev/libvirt-provider/internal/controllers.(*MachineReconciler).Start in goroutine 88
    /home/sosahu/my-workspace/libvirt-provider/internal/controllers/machine_controller.go:185 +0x298
exit status 2
```

**Comment by so-sahu** [comment]
Resolved with: https://github.com/ironcore-dev/libvirt-provider/pull/388
